### ISSUE TITLE
BUG: xarray may leave a link to file open

### ISSUE THREAD

**Issue by jklenzing** [pysat/pysat#887]
**Describe the bug**
When loading xarray data via `utils.load_netcdf`, a link to the file may be left open on some windows systems.  This creates issues  in the unit tests observed in pysat/pysatModels#89

**To Reproduce**
Look through logs associated with pysat/pysatModels#92

**Desktop (please complete the following information):**
 - OS: Windows

**Additional context**
Not noticing problems in similar xarray instruments for pysatNASA, but could be slight version differences.

**Comment by jklenzing** [comment]
Following up on this, I've compared the pysatNASA and pysatModels log for CI tests run recently on Windows with python 3.8.  Both use the same versions of xarray (0.19.0), netCDF4 (1.5.7), and pysat (3.0.1).  Not sure why the ICON xarray instruments work and the model xarray instruments fail.  The pysatModels log does show a different version of the github actions runner (2.280.3 instead of 2.280.2).

Adding `out.close()` after the following load statements in the core package
https://github.com/pysat/pysat/blob/3d33e81de2a32da9f0deea2e8a5160aa017607cf/pysat/utils/_core.py#L404-L407
should fix the issue anywhere it occurs rather than fixing it after loading in other packages.

**Comment by jklenzing** [comment]
Further testing with pysatNASA and the updated runner are working.

**Comment by rstoneback** [comment]
Nice find!

On Aug 19, 2021, at 3:40 PM, Jeff Klenzing ***@***.******@***.***>> wrote:

Adding out.close() after the following load statements in the core package

https://github.com/pysat/pysat/blob/3d33e81de2a32da9f0deea2e8a5160aa017607cf/pysat/utils/_core.py#L404-L407<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpysat%2Fpysat%2Fblob%2F3d33e81de2a32da9f0deea2e8a5160aa017607cf%2Fpysat%2Futils%2F_core.py%23L404-L407&data=04%7C01%7Crstoneba%40utdallas.edu%7C56ae4ca86d5b40789dfd08d963519c01%7C8d281d1d9c4d4bf7b16e032d15de9f6c%7C0%7C0%7C637650024462612973%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=4fc%2FpxomqM3lBetc3TRilRvQaDEoyjTAXgyaYYpbLgA%3D&reserved=0>
should fix the issue anywhere it occurs rather than fixing it after loading in other packages.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpysat%2Fpysat%2Fissues%2F887%23issuecomment-902230029&data=04%7C01%7Crstoneba%40utdallas.edu%7C56ae4ca86d5b40789dfd08d963519c01%7C8d281d1d9c4d4bf7b16e032d15de9f6c%7C0%7C0%7C637650024462622925%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=hgH9MznGT%2FpzbrYNdHOHU80%2F0qkdGQpiWFA95yUi6dY%3D&reserved=0>, or unsubscribe<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAA3N26IPPOOPKZKU3EVUM5LT5VT4RANCNFSM5COUGDUQ&data=04%7C01%7Crstoneba%40utdallas.edu%7C56ae4ca86d5b40789dfd08d963519c01%7C8d281d1d9c4d4bf7b16e032d15de9f6c%7C0%7C0%7C637650024462622925%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=sxH2EQd9xtHhzD1WLbxsWsdSbrSaAMenik0dTB0VtxA%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Crstoneba%40utdallas.edu%7C56ae4ca86d5b40789dfd08d963519c01%7C8d281d1d9c4d4bf7b16e032d15de9f6c%7C0%7C0%7C637650024462632878%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=83TOoRiDsBYS2nVatBP7na48QOqD3bF66dLcsKQW3uI%3D&reserved=0> or Android<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7Crstoneba%40utdallas.edu%7C56ae4ca86d5b40789dfd08d963519c01%7C8d281d1d9c4d4bf7b16e032d15de9f6c%7C0%7C0%7C637650024462632878%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=2mbDw8489o3YyaJe%2Fqy3HOOxy7Aw5aVFA2mrwLbRrX0%3D&reserved=0>.

**Comment by jklenzing** [comment]
Still not sure why it happens some places but not others.  Not sure how to test for this, but so far it's fixed it wherever there's been a problem.

**Comment by jklenzing** [comment]
Closing with merge of #889.
